/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStakingReward,
  IStakingRewardInterface,
} from "../../../contracts/interfaces/IStakingReward";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStakingReward__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingRewardInterface {
    return new Interface(_abi) as IStakingRewardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStakingReward {
    return new Contract(address, _abi, runner) as unknown as IStakingReward;
  }
}
